version: "3.7"
services:
  website:
    build: './containers/Website'
    image: website
    # volumes:
    #   - ./containers/Website/public_html:/var/www/html/
    ports:
      - "8089:80"
    networks:
      - games_net
    depends_on:
      - kafka
  gamemaster:
    build: ./containers/GameMaster
    image: gamemaster
    ports:
      - 9000:9000
      - 5002:5002
    networks:
      - nosql_net
      - games_net
    volumes:
      - ./containers/GameMaster/logs:/etc/logs
    depends_on:
      - kafka
  playmaster:
    build: ./containers/PlayMaster
    image: playmaster
    networks:
      - games_net
      - nosql_net
    ports:
      - 1337:1337
    environment:
      - GAME_PORT=1337
    depends_on:
      - gamemaster
      - kafka
  playmaster2:
    build: ./containers/PlayMaster
    image: playmaster
    networks:
      - games_net
      - nosql_net
    ports:
      - 1338:1338
    environment:
      - GAME_PORT=1338
    depends_on:
      - gamemaster
      - kafka
  # generator:
  #   build: ./containers/generator
  #   image: generator
  #   networks:
  #     - games_net
  #   volumes:
  #     - ./containers/generator/logs:/etc/logs
  #   depends_on:
  #     - kafka
  #     - playmaster
  zookeeper:
    image: zookeeper:3.6.0
    ports:
      - 2181:2181
    networks:
      - games_net
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "input:10:1, scores:10:1, output:10:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" 
      KAFKA_CLEANUP_POLICY: "delete"
    ports:
      - 9094:9094
      - 9092:9092
    expose:
      - "9092"
    depends_on:
      - zookeeper
    networks:
      - games_net
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: games
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - nosql_net
  auth_service:
    build: ./containers/AuthService
    image: auth_service
    ports:
      - 5010:5010
    networks:
      - sql_net
      - games_net
    depends_on:
      - mysql
    volumes:
      - ./containers/AuthService/logs:/etc/logs
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data_container:/var/lib/mysql
      - ./containers/AuthService/sql_init:/docker-entrypoint-initdb.d
    networks:
      - sql_net
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: rootpassword
volumes:
  mongodb_data_container:
  mysqldb_data_container:
networks:
  games_net:
  nosql_net:
  sql_net: