version: "3.7"
services:
  gamemaster:
    build: ./containers/GameMaster
    image: gamemaster
    networks:
      - nosql_net
      - games_net
    volumes:
      - ./containers/GameMaster/logs:/etc/logs
    depends_on:
      - kafka
  playmaster:
    build: ./containers/PlayMaster
    image: gamemaster
    networks:
      - games_net
    # volumes:
    #   - ./containers/PlayMaster/logs:/etc/logs
    depends_on:
      - gamemaster
      - mongodb
    ports:
      - 1337:1337
      - 8080:8080
    networks:
      - nosql_net
  generator:
    build: ./containers/generator
    image: generator
    ports:
      - 80:8080
    networks:
      - games_net
    volumes:
      - ./containers/generator/logs:/etc/logs
    depends_on:
      - kafka
  zookeeper:
    image: zookeeper:3.6.0
    ports:
      - 2181:2181
    networks:
      - games_net
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "input:4:1, output:4:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" 
      KAFKA_CLEANUP_POLICY: "delete"
    ports:
      - 9094:9094
      - 9092:9092
    expose:
      - "9092"
    networks:
      - games_net
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: games
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - nosql_net

volumes:
  mongodb_data_container:
networks:
  games_net:
  nosql_net: