version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: /etc/logs/logs.log
    mode: w
loggers:
  mylogger:
    level: INFO
    handlers: [file, console]
    propagate: no
root:
  level: INFO
  handlers: [file, console]